version: 2

sources:
  - name: desafiodw
    schema: desafiodw
    description: this is the sources database replica
    tables:
      - name: address
        columns:
          - name: Addressid
            description: primary key of the address table
          - name: city
          - name: stateprovinceid

      - name: businessentityaddress
        columns:
          - name: BusinessEntityid
            description: primary key of the address table
          - name: adressid

      - name: countryregion
        columns:
          - name: countryregoncode
            description: will be how was the primary key of person.countryregion table
          - name: name

      - name: person
        columns:
          - name: businessentityid
            description: primary key of the businessentityid table
          - name: firstname
          - name: lastname
          - name: middlename

      - name: stateprovince
        columns:
          - name:	stateprovinceid
            description: primary key of the stateprovince table
          - name: name
          - name: territoryid

      - name: product
        columns:
          - name: Productid
            description: primary key of the product table
          - name: name
          - name: listprice

      - name: creditcard
        columns:
          - name:	Creditcardid
            description: primary key of the creditcard table.
          - name: cardtype

      - name: personcreditcard
        columns:
          - name: BusinessEntityid
            description: primary key of the personcreditcard table.
          - name: creditcardid

      - name: salesorderdetail
        columns:
          - name:	salesorderdetailid
            description: primary key of the salesorderdetail table.
          - name: salesorderid
          - name: productid
          - name: orderqty
          - name: unitprice
          - name: unitpricediscount

      - name: salesorderheader
        columns:
          - name: salesorderid
            description: primary key of the salesorderheader table
          - name: salespersonid
          - name: subtotal
          - name: orderdate
          - name: duedate
          - name: creditcardid

      - name: salesorderreadersalesreazon
        columns:
          - name: Salesreazonid
            description: primary key for the salesordersalesreazon table
          - name: Salesorderid

      - name: salesreason
        columns:
          - name: salesreazonid
            description: primary key for the salesreazon table
          - name: name
          - name: reazontype

      - name: salesterritory
        columns:
          - name: territoryid
            description: primary key for the territoryid

          - name: name